%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%   main.m
%   Name:           Simon Craig DANIEL
%   Student Number: 25848887
%   Institution:    Stellenbosch University,
%                   Electronic Systems Laboratory (ESL)
%   Date:           March 2026
%   Version:        1.3
%   Project:        Development of a Resistojet Thruster
%   Description:    
%   This script evaluates resistojet performance for a specified propellant
%   and operating point.
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
clc; clear; close all;

% --------------------------- Design Settings --------------------------- %
% Simulation Selector
simulateThrusterDesign       = true;
designThruster               = false;
comparePropellantPerformance = false;

% Resistojet Design Configurations
cfg.species         = "R134a";  % Propellant
cfg.tank.V          = 300;      % Storage Volume (m^3)
cfg.tank.T          = 265;      % Storage Temperature (K)
cfg.tank.P          = 6.9e5;    % Storage Pressure (Pa)

cfg.Tp              = 333;      % Plenum Temperature (K) - set by heating stage
cfg.heater.ri       = 1e-3;     % Heater pipe ID (m)
cfg.heater.ro       = 2.5e-3;   % Heater pipe OD (m)
cfg.heater.length   = 300e-3;   % Heater pipe length (m)
cfg.heater.N        = 1000;     % Number of heater pipe length differentials
cfg.heater.Twall    = 520;      % Heater wall temperature (K)

cfg.p0              = 5e5;      % Chamber Pressure (Pa) - set by regulator
cfg.T0              = 600;      % Chamber Temperature (K) - set by heating stage
cfg.nozzle.ri       = 1e-3;     % Nozzle inlet radius (m)
cfg.nozzle.rt       = 0.1e-3;   % Throat radius (m)
cfg.nozzle.re       = 5.0e-3;   % Exit radius (m)
cfg.nozzle.tol      = 0e-6;     % Machining tolerance (m)
cfg.environment.pa  = 1e-7;     % Environmental Pressure (Pa)

% Required Resistojet Design Configurations
req.species        = "R134a";  % Propellant
req.tank.T         = 265;       % Storage Temperature (K)
req.tank.P         = 10e5;      % Storage Pressure (Pa)
req.p0             = 5e5;     % Chamber Pressure (Pa) - set by regulator
req.T0             = 600;       % Chamber Temperature (K) - set by heating stage
req.environment.pa = 1e-7;      % Environmental Pressure (Pa)
req.re_max         = 1e-3;     % Maximum allowable nozzle exit radius (m)
req.F_des          = 100e-3;      % Desired thrust (N)


% Propellant Comparator Design Options
opts.tank.T         = 265;          % Storage Temperature (K)
opts.tank.P         = 10e5;         % Storage Pressure (Pa)
opts.re_max         = 40e-3;        % Maximum allowable nozzle exit radius (m)
opts.Tvec           = 200:5:1100;   % Chamber Temperature Sweep (K)
opts.F_des          = 20e-3;         % Desired thrust (N)
opts.p0             = 0.1e5;          % Chamber Pressure (Pa)
opts.environment.pa = 1e-7;         % Environmental Pressure (Pa)
opts.speciesList = { ...
    ...% Practically non-condensable gases (All poor candidates for volumetric impulse)
    'Air', ...
    'Helium', ...
    'Neon', ...
    'Argon', ...
    'Krypton', ...
    'Xenon', ...
    'Hydrogen', ...
    'Deuterium', ...
    'Nitrogen', ...
    'Oxygen', ...
    'Fluorine', ...
    'NitrousOxide', ...
    'CarbonMonoxide', ...
    'CarbonDioxide', ...
    'HydrogenChloride', ...
    'Methane', ...
    'Ethylene', ...
    'Ethane', ...
    'R13', ...
    'R14', ...
    'R23', ...
    'R41', ...
    'R116', ...
    ...% Condensable inorganic molecular fluids
    'Ammonia', ...
    'Water', ...
    'HeavyWater', ...
    'SulfurDioxide', ...
    'SulfurHexafluoride', ...
    'HydrogenSulfide', ...
    'CarbonylSulfide', ...
    'Iodine', ...
    ...% Hydrocarbons
    'Propylene', ...
    'Propyne', ...
    'n-Propane', ...
    'CycloPropane', ...
    '1-Butene', ...
    'cis-2-Butene', ...
    'trans-2-Butene', ...
    'IsoButene', ...
    'n-Butane', ...
    'IsoButane', ...
    'n-Pentane', ...
    'Isopentane', ...
    'Neopentane', ...
    'Cyclopentane', ...
    'n-Hexane', ...
    'Isohexane', ...
    'CycloHexane', ...
    'n-Heptane', ...
    'n-Octane', ...
    'n-Nonane', ...
    'n-Decane', ...
    'n-Undecane', ...
    'n-Dodecane', ...
    'Benzene', ...
    'Toluene', ...
    'EthylBenzene', ...
    'o-Xylene', ...
    'm-Xylene', ...
    'p-Xylene', ...
    ...% Organic fluids (oxygenated, halogenated, heavy, and siloxanes)
    'Methanol', ...
    'Ethanol', ...
    'Acetone', ...
    'DiethylEther', ...
    'DimethylEther', ...
    'DimethylCarbonate', ...
    'EthyleneOxide', ...
    'MM', ...
    'MDM', ...
    'MD2M', ...
    'MD3M', ... 
    'MD4M', ... 
    'D4', ... 
    'D5', ...
    'D6', ... 
    'MethylOleate', ...
    'MethylPalmitate', ...
    'MethylStearate', ...  
    'MethylLinoleate', ...  
    'MethylLinolenate', ... 
    'HFE143m', ...
    'Novec649', ...
    'SES36', ...
    'Dichloroethane', ...
    ...% Refrigerants
    'R13I1', ...
    'R134a', ...
    'R236FA', ...
    'R245fa', ...
    'R1234yf', ...
    'R1234ze(E)', ...
    'R11', ...
    'R12', ...
    'R21', ...
    'R22', ...
    'R32', ...
    'R40', ...
    'R113', ...
    'R114', ...
    'R115', ...
    'R123', ...
    'R124', ...
    'R125', ...
    'R141b', ...
    'R142b', ...
    'R143a', ...
    'R152A', ...
    'R161', ...
    'R218', ...
    'R227EA', ...
    'R236EA', ...
    'R245ca', ...
    'R365MFC', ...
    'R404A', ...
    'R407C', ...
    'R410A', ...
    'R507A', ...
    'R1233zd(E)', ...
    'R1234ze(Z)', ...
    'R1243zf', ...
    'R1336mzz(E)', ...
    'RC318' ...
};
% Practically non-condensable gases
speciesList1 = { ...
    'Air', ...
    'Helium', ...
    'Neon', ...
    'Argon', ...
    'Krypton', ...
    'Xenon', ...
    'Hydrogen', ...
    'Deuterium', ...
    'Nitrogen', ...
    'Oxygen', ...
    'Fluorine', ...
    'NitrousOxide', ...
    'CarbonMonoxide', ...
    'CarbonDioxide', ...
    'HydrogenChloride', ...
    'Methane', ...
    'Ethylene', ...
    'Ethane', ...
    'R13', ...
    'R14', ...
    'R23', ...
    'R41', ...
    'R116', ...
    };
% Condensable inorganic molecular fluids
speciesList2 = { ...
    'Ammonia', ...
    'Water', ...
    'HeavyWater', ...
    'SulfurDioxide', ...
    'SulfurHexafluoride', ...
    'HydrogenSulfide', ...
    'CarbonylSulfide', ...
    'Iodine', ...
};
% Hydrocarbons
speciesList3 = { ...
    'Propylene', ...
    'Propyne', ...
    'n-Propane', ...
    'CycloPropane', ...
    '1-Butene', ...
    'cis-2-Butene', ...
    'trans-2-Butene', ...
    'IsoButene', ...
    'n-Butane', ...
    'IsoButane', ...
    'n-Pentane', ...
    'Isopentane', ...
    'Neopentane', ...
    'Cyclopentane', ...
    'n-Hexane', ...
    'Isohexane', ...
    'CycloHexane', ...
    'n-Heptane', ...
    'n-Octane', ...
    'n-Nonane', ...
    'n-Decane', ...
    'n-Undecane', ...
    'n-Dodecane', ...
    'Benzene', ...
    'Toluene', ...
    'EthylBenzene', ...
    'o-Xylene', ...
    'm-Xylene', ...
    'p-Xylene', ...
};
% Organic fluids (oxygenated, halogenated, heavy, and siloxanes)
speciesList4 = { ...
    'Methanol', ...
    'Ethanol', ...
    'Acetone', ...
    'DiethylEther', ...
    'DimethylEther', ...
    'DimethylCarbonate', ...
    'EthyleneOxide', ...
    'MM', ...
    'MDM', ...
    'MD2M', ...
    'MD3M', ...
    'MD4M', ...
    'D4', ...
    'D5', ...
    'D6', ...
    'MethylOleate', ...
    'MethylPalmitate', ...
    'MethylStearate', ...
    'MethylLinoleate', ...
    'MethylLinolenate', ...
    'HFE143m', ...
    'Novec649', ...
    'SES36', ...
    'Dichloroethane', ...
};
% Refrigerants
speciesList5 = { ...
    'R13I1', ...
    'R134a', ...
    'R236FA', ...
    'R245fa', ...
    'R1234yf', ...
    'R1234ze(E)', ...
    'R11', ...
    'R12', ...
    'R21', ...
    'R22', ...
    'R32', ...
    'R40', ...
    'R113', ...
    'R114', ...
    'R115', ...
    'R123', ...
    'R124', ...
    'R125', ...
    'R141b', ...
    'R142b', ...
    'R143a', ...
    'R152A', ...
    'R161', ...
    'R218', ...
    'R227EA', ...
    'R236EA', ...
    'R245ca', ...
    'R365MFC', ...
    'R404A', ...
    'R407C', ...
    'R410A', ...
    'R507A', ...
    'R1233zd(E)', ...
    'R1234ze(Z)', ...
    'R1243zf', ...
    'R1336mzz(E)', ...
    'RC318' ...
};
topPropellantsList = { ...
    'R13I1', ... % Thermally decomposes after 110-120 degC -> therefore not suitable for electrothermal propulsion
    'R124', ...
    'R227EA', ...
    'R245ca', ...
    'R245fa', ...
    'R134a', ...
    'R236FA', ...
    'R123', ...
    'R218', ...
    'R22', ...
    'R125', ...
    'SulfurHexafluoride', ...
    'R32', ...
    'R12', ...
    'R407C', ...
    'R1234ze(E)', ...
    'R21', ... % Thermally decomposes after 500 K to produce toxic and corrosive products
    'R410A', ...
    'R115', ...
    'R142b', ...
    'R236EA', ...
    'Novec649', ...
    'Iodine', ...
    'HeavyWater', ...
    'Water' ...
};
finalCandidates = { ...
    'R236FA',...
    'R245fa', ...
    'R134a',...
    'R1234ze(E)',...
    'R227EA',...
    'Water',...
};

% --------------------------- Design Settings --------------------------- %
if simulateThrusterDesign
    nozzle(cfg);
    %heater(cfg);
end

% --------------------------- Nozzle Designer --------------------------- %
if designThruster
    out = nozzleDesigner(req);
    disp(out);
end

% ------------------------ Propellant Comparator ------------------------ %
if comparePropellantPerformance
    results = comparePropellants(opts, finalCandidates);
end